name:                klon
version:             0.1.0.0
github:              "smaccoun/klon"
license:             BSD3
author:              "steven maccoun"
maintainer:          "theraccoun@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smaccoun/klon#readme>

dependencies:
- Cabal
- base >= 4.7 && < 5
- optparse-applicative
- text
- shelly
- higgledy
- amazonka
- amazonka-core
- amazonka-ecs
- amazonka-ec2
- microlens

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - NamedFieldPuns
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - DeriveAnyClass
  - DerivingStrategies


library:
  source-dirs: lib

executables:
  klon:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - klon

tests:
  klon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - klon
